# Generated by Django 4.0.5 on 2023-03-10 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('column_separator', models.CharField(choices=[('Comma (,)', ','), ('Semicolon (;)', ';'), ('Tab (\t)', '\t'), ('Pipe (|)', '|')], max_length=200)),
                ('string_character', models.CharField(choices=[('Double', '"'), ('Single', "'")], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('full_name', 'Full Name'), ('job', 'Job'), ('email', 'Email'), ('domain_name', 'Domain Name'), ('phone_number', 'Phone Number'), ('company_name', 'Company Name'), ('text', 'Text'), ('integer', 'Integer'), ('address', 'Address'), ('date', 'Date')], max_length=255)),
                ('order', models.IntegerField()),
                ('extra_args', models.CharField(blank=True, max_length=255)),
                ('range_min', models.IntegerField(blank=True, null=True)),
                ('range_max', models.IntegerField(blank=True, null=True)),
                ('schema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.dataschema')),
            ],
        ),
    ]
