# Generated by Django 4.0.5 on 2023-03-10 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='data_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='column',
            name='schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.dataschema'),
        ),
        migrations.AlterField(
            model_name='dataschema',
            name='column_separator',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dataschema',
            name='string_character',
            field=models.CharField(max_length=200),
        ),
    ]
