# Generated by Django 4.0.5 on 2023-03-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_alter_column_data_type_alter_column_schema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='extra_args',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
